In [1]:
import sys
sys.path.append("../src")

In [2]:
from Fasttext.Connect_Database import connect
from preprocessing import clean,stopword
import pandas as pd
import fasttext
from sklearn.model_selection import train_test_split
import csv

In [3]:
app = connect()
df = pd.DataFrame(app.load_data_VnExpress())

c:\Users\admin\Data\anaconda\Lib\site-packages\pymongo\pyopenssl_context.py:355: CryptographyDeprecationWarning: Parsed a serial number which wasn't positive (i.e., it was negative or zero), which is disallowed by RFC 5280. Loading this certificate will cause an exception in a future release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

In [4]:
df[['topic', 'subtopic', 'content']].head(10)

     topic       subtopic                                            content
0  Thời sự      Chính trị  Chiều 19/8, Tổng Bí thư Tô Lâm làm việc với Ba...
1  Thời sự      Chính trị  Tổng Bí thư nhấn mạnh việc chuẩn bị, tổ chức c...
2  Thời sự      Chính trị  Người đứng đầu Đảng đề nghị các cơ quan triển ...
3  Thời sự      Chính trị  Đồng thời, Tổng Bí thư lưu ý công tác đón tiếp...
4  Thời sự      Chính trị  Tổng Bí thư lưu ý trong dịp này, đặc biệt là v...
5  Thời sự      Chính trị  Theo báo cáo của Ban Tuyên giáo và Dân vận Tru...
6  Thời sự      Chính trị  Các hạng mục hạ tầng trọng yếu chuẩn bị cho sự...
7  Thời sự  Kỷ nguyên mới  Tháng 8/1945, cuộc tổng khởi nghĩa giành chính...
8  Thời sự      Chính trị  Để chuẩn bị cho lễ diễu binh, diễu hành kỷ niệ...
9  Thời sự      Chính trị  Riêng lực lượng diễu binh, diễu hành gồm 4 khố...

In [5]:
def process_texts(texts):
    cleaned = [clean(str(t)) for t in texts]
    processed = stopword(cleaned)
    return processed

In [6]:
df['clean_content'] = process_texts(df['content'])

In [7]:
df = df[
    ~df['subtopic'].isin(['Ảnh']) &
    ~df['topic'].isin(['Thể thao'])
]
counts = df['subtopic'].value_counts()
df = df[df['subtopic'].isin(counts[counts >= 1000].index)]

In [8]:
df['label'] = '__label__' + df['topic'].str.replace(' ', '_') + '__' + df['subtopic'].str.replace(' ', '_')

In [9]:
df.head(10)

,content,subtopic,title,topic,clean_content,label
0,"Chiều 19/8, Tổng Bí thư Tô Lâm làm việc với Ba...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,chiều 19 8 tổng bí thư tô lâm ban đạo trung ươ...,__label__Thời_sự__Chính_trị
1,"Tổng Bí thư nhấn mạnh việc chuẩn bị, tổ chức c...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,tổng bí thư nhấn chuẩn tổ chức hoạt động kỷ ni...,__label__Thời_sự__Chính_trị
2,Người đứng đầu Đảng đề nghị các cơ quan triển ...,Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,đứng đầu đảng đề nghị quan triển khai hiệu kế ...,__label__Thời_sự__Chính_trị
3,"Đồng thời, Tổng Bí thư lưu ý công tác đón tiếp...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,đồng thời tổng bí thư lưu công tác đón tiếp đạ...,__label__Thời_sự__Chính_trị
4,"Tổng Bí thư lưu ý trong dịp này, đặc biệt là v...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,tổng bí thư lưu dịp đặc biệt du đổ thủ đô hà n...,__label__Thời_sự__Chính_trị
5,Theo báo cáo của Ban Tuyên giáo và Dân vận Tru...,Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,báo cáo ban tuyên giáo dân vận trung ương công...,__label__Thời_sự__Chính_trị
6,Các hạng mục hạ tầng trọng yếu chuẩn bị cho sự...,Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,hạng mục hạ tầng trọng yếu chuẩn kiện hoàn thà...,__label__Thời_sự__Chính_trị
7,"Tháng 8/1945, cuộc tổng khởi nghĩa giành chính...",Kỷ nguyên mới,Mỗi người dân được tặng 100.000 đồng dịp Quốc ...,Thời sự,8 1945 tổng khởi nghĩa giành quyền thành công ...,__label__Thời_sự__Kỷ_nguyên_mới
8,"Để chuẩn bị cho lễ diễu binh, diễu hành kỷ niệ...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,chuẩn lễ diễu binh diễu hành kỷ niệm 80 mạng t...,__label__Thời_sự__Chính_trị
9,"Riêng lực lượng diễu binh, diễu hành gồm 4 khố...",Chính trị,Tổng Bí thư: Lễ diễu binh phải thể hiện được v...,Thời sự,lực diễu binh diễu hành 4 khối nghi trượng 43 ...,__label__Thời_sự__Chính_trị

In [10]:
df['label'].value_counts()

label
__label__Sức_khỏe__Tin_tức                       7460
__label__Thế_giới__Tư_liệu                       4173
__label__Thế_giới__Quân_sự                       4067
__label__Kinh_doanh__Doanh_nghiệp                3848
__label__Sức_khỏe__Sống_khỏe                     3564
__label__Giải_trí__Giới_sao                      3494
__label__Đời_sống__Nhịp_sống                     3303
__label__Bất_động_sản__Thị_trường                2781
__label__Kinh_doanh__Quốc_tế                     2728
__label__Thế_giới__Cuộc_sống_đó_đây              2715
__label__Giáo_dục__Tin_tức                       2620
__label__Thế_giới__Phân_tích                     2519
__label__Pháp_luật__Hồ_sơ_phá_án              2239
__label__Giải_trí__Phim                          2184
__label__Sức_khỏe__Các_bệnh                      2131
__label__Thời_sự__80_năm_Quốc_khánh              2089
__label__Kinh_doanh__Vĩ_mô                       1987
__label__Đời_sống__Bài_học_sống                  1965
__label__Du_lịch__Điểm_đến                       1912
__label__Đời_sống__Tổ_ấm                         1884
__label__Khoa_học_công_nghệ__Thiết_bị            1685
__label__Kinh_doanh__Kinh_tế_vùng                1663
__label__Giải_trí__Thời_trang                    1652
__label__Giải_trí__Nhạc                          1651
__label__Xe__Thị_trường                          1530
__label__Thời_sự__Chính_trị                      1477
__label__Kinh_doanh__Chứng_khoán                 1432
__label__Thời_sự__Giao_thông                     1424
__label__Khoa_học_công_nghệ__Chuyển_đổi_số       1353
__label__Xe__V-Car                               1319
__label__Kinh_doanh__Hàng_hóa                    1317
__label__Bất_động_sản__Không_gian_sống           1305
__label__Khoa_học_công_nghệ__AI                  1278
__label__Sức_khỏe__Vaccine                       1200
__label__Kinh_doanh__NetZero                     1135
__label__Khoa_học_công_nghệ__Đổi_mới_sáng_tạo    1108
__label__Kinh_doanh__Ebank                       1104
__label__Thời_sự__Kỷ_nguyên_mới                  1055
__label__Giáo_dục__Du_học                        1042
__label__Du_lịch__Ẩm_thực                        1036
__label__Giải_trí__Sách                          1007
__label__Du_lịch__Tư_vấn                          756
__label__Bất_động_sản__Tư_vấn                     286
__label__Pháp_luật__Tư_vấn                         36
Name: count, dtype: int64

In [11]:
df['format'] = df['label'] + ' ' + df['clean_content']
max_count= 1500
balanced_data = (df.groupby('label', group_keys=False, as_index=False).apply(lambda x: x.sample(max_count, replace=True)).reset_index(drop=True))

train, test = train_test_split(balanced_data, test_size=0.2, random_state=42)
train['format'].to_csv("../Data/processed/dataset_train.txt",index=False, header=False,sep='\n', quoting=csv.QUOTE_NONE, escapechar='\\')
test['format'].to_csv("../Data/processed/dataset_test.txt",index=False, header=False,sep='\n', quoting=csv.QUOTE_NONE, escapechar='\\')
df['format'].to_csv('../Data/processed/train.txt', index=False, header=False, sep='\n',quoting=csv.QUOTE_NONE,escapechar='\\')

C:\Users\admin\AppData\Local\Temp\ipykernel_35136\3722749065.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_data = (df.groupby('label', group_keys=False, as_index=False).apply(lambda x: x.sample(max_count, replace=True)).reset_index(drop=True))

In [12]:
pd.set_option('display.max_rows', None)
print(balanced_data['label'].value_counts())

label
__label__Bất_động_sản__Không_gian_sống           1500
__label__Bất_động_sản__Thị_trường                1500
__label__Kinh_doanh__Vĩ_mô                       1500
__label__Pháp_luật__Hồ_sơ_phá_án              1500
__label__Pháp_luật__Tư_vấn                       1500
__label__Sức_khỏe__Các_bệnh                      1500
__label__Sức_khỏe__Sống_khỏe                     1500
__label__Sức_khỏe__Tin_tức                       1500
__label__Sức_khỏe__Vaccine                       1500
__label__Thế_giới__Cuộc_sống_đó_đây              1500
__label__Thế_giới__Phân_tích                     1500
__label__Thế_giới__Quân_sự                       1500
__label__Thế_giới__Tư_liệu                       1500
__label__Thời_sự__80_năm_Quốc_khánh              1500
__label__Thời_sự__Chính_trị                      1500
__label__Thời_sự__Giao_thông                     1500
__label__Thời_sự__Kỷ_nguyên_mới                  1500
__label__Xe__Thị_trường                          1500
__label__Xe__V-Car                               1500
__label__Đời_sống__Bài_học_sống                  1500
__label__Đời_sống__Nhịp_sống                     1500
__label__Kinh_doanh__Quốc_tế                     1500
__label__Kinh_doanh__NetZero                     1500
__label__Kinh_doanh__Kinh_tế_vùng                1500
__label__Giải_trí__Phim                          1500
__label__Bất_động_sản__Tư_vấn                    1500
__label__Du_lịch__Tư_vấn                         1500
__label__Du_lịch__Điểm_đến                       1500
__label__Du_lịch__Ẩm_thực                        1500
__label__Giáo_dục__Du_học                        1500
__label__Giáo_dục__Tin_tức                       1500
__label__Giải_trí__Giới_sao                      1500
__label__Giải_trí__Nhạc                          1500
__label__Giải_trí__Sách                          1500
__label__Kinh_doanh__Hàng_hóa                    1500
__label__Giải_trí__Thời_trang                    1500
__label__Khoa_học_công_nghệ__AI                  1500
__label__Khoa_học_công_nghệ__Chuyển_đổi_số       1500
__label__Khoa_học_công_nghệ__Thiết_bị            1500
__label__Khoa_học_công_nghệ__Đổi_mới_sáng_tạo    1500
__label__Kinh_doanh__Chứng_khoán                 1500
__label__Kinh_doanh__Doanh_nghiệp                1500
__label__Kinh_doanh__Ebank                       1500
__label__Đời_sống__Tổ_ấm                         1500
Name: count, dtype: int64

In [13]:
model = fasttext.train_supervised(
    input="../Data/processed/dataset_train.txt",
    lr=0.1,
    epoch=100,
    wordNgrams=3,
    dim=100,
    loss='softmax'
)

In [14]:
result = model.test("../Data/processed/dataset_test.txt")
print(f"Số mẫu test: {result[0]}")
print(f"Độ chính xác (precision): {result[1]:.4f}")
print(f"Độ bao phủ (recall): {result[2]:.4f}")
print(f"F1-score: {2 * result[1] * result[2] / (result[1] + result[2]):.4f}")

Số mẫu test: 13200
Độ chính xác (precision): 0.7970
Độ bao phủ (recall): 0.7970
F1-score: 0.7970

In [15]:
model.save_model("../models/Fasttext/model_1.bin")

In [16]:
df_Reddit = pd.DataFrame(app.load_data())
df_Reddit['clean_content'] = process_texts(df_Reddit['content'])

In [17]:
df_Reddit.head(5)

,link,author,comments,content,date,image_link,subreddit,title,upvotes,video_link,clean_content
0,https://www.reddit.com/r/TroChuyenLinhTinh/com...,Friendly-Lie5849,37,Bộ phim tuyên truyền chủ nghĩa dân tộc cực đoa...,2025-08-22 07:25:50,None,TroChuyenLinhTinh,Những gì đang diễn ra ở Trung Quốc đang dần lặ...,157,None,phim tuyên truyền chủ nghĩa dân tộc cực đoan m...
1,https://www.reddit.com/r/vozforums/comments/1m...,TinNT0409,1,"Chào mọi người, đợt này mình có dùng Mathpix đ...",2025-08-22 07:23:33,https://external-preview.redd.it/kqhxR96oyl5gx...,vozforums,Phần mềm quét công thức sang Word miễn phí tha...,2,None,chào đợt mathpix quét công thức đc 10 lượt viế...
2,https://www.reddit.com/r/TroChuyenLinhTinh/com...,Weekly_Top7078,3,Trước kì kinh bao nhiêu ngày thì an toàn?,2025-08-22 07:07:46,None,TroChuyenLinhTinh,Ngày an toàn,0,None,kì kinh bao nhiêu an toàn
3,https://www.reddit.com/r/VietNamNation/comment...,Ambitious-Fan-9831,18,ờm bỏ qua tỉ lệ gái đẹp ra thì tao thấy bề nổi...,2025-08-22 07:04:09,None,VietNamNation,Thái Lan có phải là 1 hình mẫu nước đáng sống ...,16,None,ờm tỉ lệ gái đẹp tao bề nổi thái lọ cánh tả số...
4,https://www.reddit.com/r/vozforums/comments/1m...,Nicklas0704,3,"Hi các bác, e làm mmo có dư 1 ít, cụ thể là kh...",2025-08-22 14:03:21,None,vozforums,Hiện tại nên bỏ tiền vào đâu ?,0,None,hi e mmo dư 1 cụ thể 10 tỉ tham gia đầu hiện e...

In [18]:
df_Reddit = df_Reddit[
    df_Reddit['clean_content'].notna() &                   
    (df_Reddit['clean_content'].str.strip().str.lower() != 'none') &
    (df_Reddit['clean_content'].str.strip() != '')
]

In [19]:
df_Reddit = df_Reddit[['author', 'title','clean_content', 'content']]
df_Reddit.head(2)

,author,title,clean_content,content
0,Friendly-Lie5849,Những gì đang diễn ra ở Trung Quốc đang dần lặ...,phim tuyên truyền chủ nghĩa dân tộc cực đoan m...,Bộ phim tuyên truyền chủ nghĩa dân tộc cực đoa...
1,TinNT0409,Phần mềm quét công thức sang Word miễn phí tha...,chào đợt mathpix quét công thức đc 10 lượt viế...,"Chào mọi người, đợt này mình có dùng Mathpix đ..."

In [20]:
labels = []
scores = []
for text in df_Reddit['clean_content']:
    if not isinstance(text, str):
        text = ""
    text_clean = text.replace("\n", " ").strip()
    prediction = model.predict(text_clean)
    labell = prediction[0][0].replace("__label__", "")
    score = prediction[1][0]
    labels.append(labell)
    scores.append(score)
df_Reddit['label'] = labels
df_Reddit['score'] = scores

In [21]:
df_Reddit.head(10)

,author,title,clean_content,content,label,score
0,Friendly-Lie5849,Những gì đang diễn ra ở Trung Quốc đang dần lặ...,phim tuyên truyền chủ nghĩa dân tộc cực đoan m...,Bộ phim tuyên truyền chủ nghĩa dân tộc cực đoa...,Giải_trí__Phim,0.477290
1,TinNT0409,Phần mềm quét công thức sang Word miễn phí tha...,chào đợt mathpix quét công thức đc 10 lượt viế...,"Chào mọi người, đợt này mình có dùng Mathpix đ...",Giáo_dục__Tin_tức,0.458249
2,Weekly_Top7078,Ngày an toàn,kì kinh bao nhiêu an toàn,Trước kì kinh bao nhiêu ngày thì an toàn?,Thế_giới__Cuộc_sống_đó_đây,0.363906
3,Ambitious-Fan-9831,Thái Lan có phải là 1 hình mẫu nước đáng sống ...,ờm tỉ lệ gái đẹp tao bề nổi thái lọ cánh tả số...,ờm bỏ qua tỉ lệ gái đẹp ra thì tao thấy bề nổi...,Thế_giới__Tư_liệu,0.357446
4,Nicklas0704,Hiện tại nên bỏ tiền vào đâu ?,hi e mmo dư 1 cụ thể 10 tỉ tham gia đầu hiện e...,"Hi các bác, e làm mmo có dư 1 ít, cụ thể là kh...",Kinh_doanh__Hàng_hóa,0.553686
5,Chunghiacanhanvidai,Đừng Đánh Giá Tự Do Xã Hội Bằng Giáo Điều Phươ...,đừng đánh giá xã hội giáo phương tây trần trụi...,Đừng Đánh Giá Tự Do Xã Hội Bằng Giáo Điều Phươ...,Giải_trí__Sách,0.538289
7,117431853211,Xin mọi người cho em lời khuyên,nay 17 sống bình chí thể coi êm đềm bất kỳ biế...,"Năm nay em 17 tuổi, cuộc sống rất bình thường,...",Đời_sống__Tổ_ấm,0.314655
8,LeeTuneVane,Con BHP rồi mẹ ạ .Nếu may mắn thì gia đình mìn...,bhp mẹ may mắn gia đình kinh tế mẹ bát cơm can...,Con BHP rồi mẹ ạ .Nếu may mắn thì gia đình mìn...,Đời_sống__Tổ_ấm,0.672545
10,dahoodcashseller,Sỹ con chạy xe quá lẹ bắt chước cha,welp ae kết tụi chạy 70km h ko đội nón tông xo...,Welp chắc ae cũng biết cái kết rồi tụi này chạ...,Thế_giới__Cuộc_sống_đó_đây,0.360535
11,fishmeaterm,Kêu gọi toàn dân VietNamNation vào trị bọn Pod...,kêu gọi toàn dân đảo vietnamnation trị bọn pod...,Kêu gọi toàn dân đảo VietNamNation vào trị bọn...,Kinh_doanh__NetZero,0.507341

In [22]:
for idx, row in df_Reddit.head(50).iterrows():
    print(f"Author: {row['author']}")
    print(f"Title: {row['title']}")
    print(f"Content: {row['content'][:200]}...")
    print(f"Label: {row['label']}")
    print(f"Score: {row['score']:.3f}")
    print("-"*60)

Author: Friendly-Lie5849
Title: Những gì đang diễn ra ở Trung Quốc đang dần lặp lại ở Việt Nam
Content: Bộ phim tuyên truyền chủ nghĩa dân tộc cực đoan Mưa Đỏ aka Máu Kinh đang được truyền thông, dư luận viên, bò đỏ, Sô-Vanh con tung hê hết lời. Phim hiện đã thu về 28 tỷ đồng vào ngày đầu công chiếu là ...
Label: Giải_trí__Phim
Score: 0.477
------------------------------------------------------------
Author: TinNT0409
Title: Phần mềm quét công thức sang Word miễn phí thay thế Mathpix, Mathtype, Equation mặc định trong Word
Content: Chào mọi người, đợt này mình có dùng Mathpix để quét công thức nhưng đc có 10 lượt nên Viết luôn app thay thế miễn phí [AuraLateX](https://auravsoftware.com/chuyen-cong-thuc-toan-sang-word/)...
Label: Giáo_dục__Tin_tức
Score: 0.458
------------------------------------------------------------
Author: Weekly_Top7078
Title: Ngày an toàn
Content: Trước kì kinh bao nhiêu ngày thì an toàn?...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.364
------------------------------------------------------------
Author: Ambitious-Fan-9831
Title: Thái Lan có phải là 1 hình mẫu nước đáng sống cho người Việt?
Content: ờm bỏ qua tỉ lệ gái đẹp ra thì tao thấy bề nổi của Thái lọ có nhiều cái khá cánh tả đáng để sống.
Chính trị: đa đảng có thể tha hồ biểu tình chống chính phủ, (tk vua và quân đội hoàng gia kiểu hê hê t...
Label: Thế_giới__Tư_liệu
Score: 0.357
------------------------------------------------------------
Author: Nicklas0704
Title: Hiện tại nên bỏ tiền vào đâu ?
Content: Hi các bác, e làm mmo có dư 1 ít, cụ thể là khoảng 10 tỉ, nhưng em đó giờ không tham gia đầu tư gì cả, chỉ thuần làm và làm thôi, hiện tại e đang nhét bank lấy lãi tiết kiệm
Nhưng e có nghe ngóng là đ...
Label: Kinh_doanh__Hàng_hóa
Score: 0.554
------------------------------------------------------------
Author: Chunghiacanhanvidai
Title: Đừng Đánh Giá Tự Do Xã Hội Bằng Giáo Điều Phương Tây: Sự Thật Trần Trụi Về Hệ Thống Dân Chủ Thần Quyền
Content: Đừng Đánh Giá Tự Do Xã Hội Bằng Giáo Điều Phương Tây: Sự Thật Trần Trụi Về Dân Chủ Thần Quyền

Tao đồng ý với mày: cách đánh giá tự do xã hội của phương Tây, với các chỉ số như Freedom House, thường m...
Label: Giải_trí__Sách
Score: 0.538
------------------------------------------------------------
Author: 117431853211
Title: Xin mọi người cho em lời khuyên
Content: Năm nay em 17 tuổi, cuộc sống rất bình thường, thậm chí có thể coi là êm đềm. Chưa từng có bất kỳ một biến cố hay tại nạn nào từng xảy đến với em cả. Nhưng mà em luôn có cảm giác không thực với bản th...
Label: Đời_sống__Tổ_ấm
Score: 0.315
------------------------------------------------------------
Author: LeeTuneVane
Title: Con BHP rồi mẹ ạ .Nếu may mắn thì gia đình mình có thêm kinh tế, Còn không thì lại về xin mẹ bát cơm canh cà mẹ nhé
Content: Con BHP rồi mẹ ạ .Nếu may mắn thì gia đình mình có thêm kinh tế, Còn không thì lại về xin mẹ bát cơm canh cà mẹ nhé...
Label: Đời_sống__Tổ_ấm
Score: 0.673
------------------------------------------------------------
Author: dahoodcashseller
Title: Sỹ con chạy xe quá lẹ bắt chước cha
Content: Welp chắc ae cũng biết cái kết rồi tụi này chạy chắc 70km/h ko đội nón mà tông xong tụi nó ko bị j là ghê đó đúng là thổ đu đua xe...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.361
------------------------------------------------------------
Author: fishmeaterm
Title: Kêu gọi toàn dân VietNamNation vào trị bọn Podo ở Baocheng ( Đảo Hải Nam)
Content: Kêu gọi toàn dân đảo VietNamNation vào trị bọn Podo ở Baocheng ( Đảo Hải Nam).
Kêu gọi toàn dân đảo VietNamNation vào trị bọn Podo ở Baocheng ( Đảo Hải Nam).
Kêu gọi toàn dân đảo VietNamNation vào trị...
Label: Kinh_doanh__NetZero
Score: 0.507
------------------------------------------------------------
Author: Ok-Mix-1952
Title: Rời Hà Nội vì không tìm được việc, về KCN làm IT MES trái ngành… giờ tôi học AI để quay lại, liệu có khả thi?
Content: Tôi một sinh viên CNTT mới ra trường mảng lập trình di động.

Sau khi tốt nghiệp, tôi từng đắn đo mãi có nên ở Hà Nội để tìm việc cho đúng ngành hay không. Nhưng cuối cùng, tôi quyết định về khu công ...
Label: Giáo_dục__Tin_tức
Score: 0.306
------------------------------------------------------------
Author: HistoricalVacation82
Title: Việt nam quá yên bình, pewpew ơi vào đây coi.
Content: Không cần xả súng chi mà tốn tiền, cứ cận chiến vầy mới đúng chất giang hồ đông lào.Không cần xả súng chi mà tốn tiền, cứ cận chiến vầy mới đúng chất giang hồ đông lào.Không cần xả súng chi mà tốn tiề...
Label: Đời_sống__Bài_học_sống
Score: 0.414
------------------------------------------------------------
Author: Ancient_Phoenix_1912
Title: Tư vấn
Content: Chào mọi người, em hiện tại là sinh viên ngành sức khoẻ mới ra trường, đến nay vẫn chưa xin được việc vì chưa có kinh nghiệm và gia đình cũng kì vọng lương cao mới cho làm (trên 8tr), hiện tại ở nhà c...
Label: Khoa_học_công_nghệ__Đổi_mới_sáng_tạo
Score: 0.243
------------------------------------------------------------
Author: HistoricalVacation82
Title: Kiếm bánh mì mà bánh này hơi khó ăn
Content: Cái kiểu chặn xe kiểu này, bữa giờ nhập viện bao nhiêu thằng rồi, đúng conan việt nam liều như chó.Cái kiểu chặn xe kiểu này, bữa giờ nhập viện bao nhiêu thằng rồi, đúng conan việt nam liều như chó.Cá...
Label: Xe__V-Car
Score: 0.313
------------------------------------------------------------
Author: Mother-Exchange-7346
Title: lỗi khi download phim bằng abyss video downloader  Failed to deserialize JSON
Content: [cho e hỏi ai bị lỗi này chưa và cách fix như nào ạ ? e cảm ơn ](https://preview.redd.it/9exefqkx7ikf1.png?width=1748&format=png&auto=webp&s=32f2bfad0c4c13051b94e25ee3d887e485ac0262)...
Label: Khoa_học_công_nghệ__AI
Score: 0.952
------------------------------------------------------------
Author: Melodic_Penalty9026
Title: Tiền đẻ ra tiền ?
Content: Em mới được hưởng trc 1 ít từ gia đình, cụ thể 2 tỷ do mới bán đc đất. Mới u30 thôi, lao động trí óc vẫn làm công ăn lương bt nhưng em sợ sẽ bị đào thải sớm khi XH càng ngày càng phát triển. Cầm 2 tỷ ...
Label: Bất_động_sản__Thị_trường
Score: 0.467
------------------------------------------------------------
Author: LeeTuneVane
Title: Phấn đấu GDP bình quân đầu người đạt 8.500 USD vào năm 2030
Content: GDP đầu người ở Cubố đạt 12.000 USD, còn cao hơn cả Thái Lan và gần ngang Nhật, Hàn con c-h-ó của Mỹ mà sao người dân vịt lăm ta lại phải quyên góp cho Cubố vậy???...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.695
------------------------------------------------------------
Author: PoolOk8863
Title: thoát bẫy hay sụp hố ?? dân việt nam làm gì còn cơ hội thoát bẫy thu nhập trung bình khi nguồn lực đã cạn dân số chưa giàu đã già và bệnh tật bủa vây
Content: Thực ra để tăng trưởng thì nó cần có nhiều yếu tố + chính sách phối hợp. Nhưng lao động giá rẻ thì dùng hết mẹ rồi, dân số bắt đầu già rồi, tài nguyên thì hết,, công nghệ mới thì ko có, giải ngân đầu ...
Label: Thời_sự__Kỷ_nguyên_mới
Score: 0.421
------------------------------------------------------------
Author: Early_Yesterday443
Title: New sub about Vietnam!??
Content: Reddit vừa đẩy cái thông báo promo cho tôi về cái sub này. vào dòm thì mới tạo tháng trước luôn. Là của ông nào trong này lập ra hả? Ngó qua vài bài thì thấy trao đổi khá cởi mở và văn minh....
Label: Đời_sống__Bài_học_sống
Score: 0.176
------------------------------------------------------------
Author: Frosty_Border_5113
Title: !!!
Content: Chuyện là bạn t có chơi crypto và nó định vay crypto ở web đen. Vậy mn cho t hỏi việc vay bằng crypto thường là thế chấp hay phải có thông tin cá nhân để đảm bảo khoản vay nhỉ?...
Label: Đời_sống__Bài_học_sống
Score: 0.933
------------------------------------------------------------
Author: LeeTuneVane
Title: Phấn đấu mỗi tháng đảng sẽ tổ chức concert xiếc khỉ quốc gia mở rộng, để cho bò đỏ dân đen có dịp sục chéo ngao nghễ quên đi nghèo đói sau những ngày làm việc vất vả mà không có đủ ăn
Content: Phấn đấu mỗi tháng đảng sẽ tổ chức concert xiếc khỉ quốc gia mở rộng, để cho bò đỏ dân đen có dịp sục chéo ngao nghễ quên đi nghèo đói sau những ngày làm việc vất vả mà không có đủ ăn...
Label: Thời_sự__80_năm_Quốc_khánh
Score: 0.818
------------------------------------------------------------
Author: Ambitious-Fan-9831
Title: Toàn thể ae report hoặc block tk Vua Nam và những tk dùng bot đi spam
Content: Đụ mẹ đi đâu cũng thấy con dog bot đó spam...
Label: Đời_sống__Tổ_ấm
Score: 0.925
------------------------------------------------------------
Author: funny_why
Title: Sinh viên IT và Laptop gaming
Content: Cho mình hỏi tại sao hay thấy trên mạng mọi người tư vấn cho sinh viên, đặc biệt là sinh viên IT mua laptop gaming vậy ?

Laptop gaming đồng ý là cấu hình khá nhưng nó vừa nặng, vừa nóng, vừa mau hết ...
Label: Giáo_dục__Du_học
Score: 0.362
------------------------------------------------------------
Author: NgoBachDien
Title: Công bằng mà nói, bọn này sống dai như gián, cứ trơ trơ mãi, trong khi những nạn nhân vô tội
Content: Công bằng mà nói, bọn này sống dai như gián, cứ trơ trơ mãi, trong khi những nạn nhân vô tội thì nằm xuống không bao giờ trở lại.

Sài Gòn cách đây 5 năm, đua xe, cướp giật tung hoành. Nhưng khi công ...
Label: Thời_sự__80_năm_Quốc_khánh
Score: 0.340
------------------------------------------------------------
Author: Chunghiacanhanvidai
Title: Xã hội phương Tây điên mẹ nó rồi. Bê đê bây giờ ngoài thú vui tôn thờ hồi giáo thì tụi nó tôn thờ cộng sản
Content: Thổ tả phương Tây điên mẹ óc rồi.

Bê đê chuyển giới hết thờ hồi giáo nhập cư bây giờ chuyển sang thờ Liên xô nó mới vừa hài vừa ngu vừa điên.

Mẹ nó chơi chính trị tự hủy thế này thì chịu rồi.

Tron...
Label: Thế_giới__Tư_liệu
Score: 0.809
------------------------------------------------------------
Author: Ok-Praline1660
Title: muốn nghỉ làm
Content: ko biết có bạn nào đã/đang trả qua cảm giác giống mình không. mỗi ngày đi làm với mình như cực hình, chỉ toàn cảm thấy toxic. mình nhận ra gần đây mình đã hết hứng thú/đam mê với công việc rồi. rất mu...
Label: Đời_sống__Tổ_ấm
Score: 0.364
------------------------------------------------------------
Author: Majestic-Level-7664
Title: ?????
Content: Các ông có thể cho toy bíc điều gì ở con gái khiến con trai bị ấn tượng không(ấn tượng thôi chứ không phải thích hay crush đâu nha) kiểu như về nhan sắc hay học vấn hoặc một khoảnh khắc nào đó chẳng h...
Label: Giáo_dục__Du_học
Score: 0.527
------------------------------------------------------------
Author: PoolOk8863
Title: Hàn Quốc thoát cộng nhờ vào chính sách diệt sạch lũ thân bắc triều & châm chích chế độ +s Việt Nam đã xuất khẩu nhiều cô dâu & culi cho cứ hàn
Content: 1 người làm HDV du lịch kể lại có đợt nó dẫn đoàn khách du lịch HQ về Bình Định nơi vốn trc kia là đại bản doanh của sư đoàn Mãnh hổ Đại Hàn thì có 1 ông khách độ tuổi trung niên nói với nó... Ngày xư...
Label: Giải_trí__Sách
Score: 0.329
------------------------------------------------------------
Author: Big_Employment_2791
Title: Ekip này làm kịch bản hay nhé....
Content: Mình thấy mấy bạn trẻ làm kịch bản rất là hay...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.813
------------------------------------------------------------
Author: LeeTuneVane
Title: Tí có thằng nào trong đám đông xếp hàng xem xiếc khỉ mà giấm dạp, cầm trái bom hay cầm dao xiên vài người trả thù xã hội thì đúng là quá absolute cinema luôn phải không Thanos à
Content: Tí có thằng nào trong đám đông xếp hàng xem xiếc khỉ mà giấm dạp, cầm trái bom hay cầm dao xiên trả thù xã hội thì đúng là quá absolute cinema luôn phải không u/Thanos_SlayerCongSan à...
Label: Đời_sống__Tổ_ấm
Score: 0.293
------------------------------------------------------------
Author: hoisyconvien
Title: hoisycon lý giải lý do tạo sao thằng chó đen lại đứng chắn xe của người boi phố và cập nhựt tình hình của nó
Content: Lý do: Trích cmt của 1 tml nào đấy trong này:

"Vì chúng nó nghĩ rằng xe phải tránh chúng nó. M cứ đi đường là thấy chó vàng sang đường giữa lúc đèn xanh, nhiều lắm. Tư duy ông trời con mà, nhưng mà g...
Label: Sức_khỏe__Tin_tức
Score: 0.691
------------------------------------------------------------
Author: Extension_Order6135
Title: Lý do thật của việc ăn xin hộ Cuba và nhồi trend yêu nước
Content: Vài tình hình thời sự thực tế mà các con ma cần phải nắm bắt cho rõ

**1. Sự thật đằng sau việc ăn xin hộ Cuba**

Ai cũng thấy đm clgt khi tự dưng bùng nổ trend ăn xin hộ thằng Cuba ở bên kia bán cầu ...
Label: Đời_sống__Bài_học_sống
Score: 0.482
------------------------------------------------------------
Author: Bakesucvat2486
Title: ⚠️ Khôi phục văn hóa Nam-kỳ tập 100 : Hư/banh và hỏng !! Khác biệt Nam-kỳ và cái đám tonkin ‼️
Content: Cộng hòa Nam Kỳ sẽ trở lợi, Liên bang Đại Nam sẽ được khôi phục. Cầu nguyện những câu chuyện ý nghĩa nầy sẽ đến được tới tai của anh chị em Cao nguyên, Khmer, Chàm, Minh hương, Cao Đài, Hòa Hảo, Phật ...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.220
------------------------------------------------------------
Author: khanh2808
Title: Kì thi tiếng Anh đầu vào của đại học FPT
Content: Em là tân sinh viên của đại học FPT Hà Nội năm nay, em khá yếu tiếng Anh và chỉ còn hơn 10 ngày nữa là đến kì kiểm tra tiếng Anh đầu vào. Em đã tìm kiếm nhiều nơi nhưng không thể tìm thấy đề kiểm tra ...
Label: Giáo_dục__Tin_tức
Score: 0.988
------------------------------------------------------------
Author: Sensitive-Ad-751
Title: No! No!
Content: No !

Những tội ác cụ thể của cán bộ cộng sản Việt Nam từ 1975 đến nay

Phân loại theo các lĩnh vực chính:

⚖️ Tội vi phạm nhân quyền:

Bắt giam trái pháp luật người bất đồng chính kiến, tín đồ tôn gi...
Label: Giải_trí__Sách
Score: 0.273
------------------------------------------------------------
Author: Sensitive-Ad-751
Title: Vua Nam khai dân trí và PR cho lũ "dân chủ"!
Content: Bọn Chống Cộng Bằng Mõm Ấy Mà! - Công Việc Cụ Thể Của Một Người Hoạt Động Là Gì?

---

TRẪM, NAM ĐẾ, NAM KỲ PHỔ ĐỘ-QUANG VINH VỸ ĐẠI! Đem chế độ quân chủ trở lại.

TRẪM! NAM ĐẾ!
NAM KỲ PHỔ ĐỘ-QUAN...
Label: Giải_trí__Sách
Score: 0.479
------------------------------------------------------------
Author: muki_hatchune
Title: Lời khuyên cho sinh viên đang mất phương hướng ngành CNTT?
Content: Chào mọi người, em hiện đang học năm cuối ở 1 trường đại học ở Mỹ ngành Software Engineering. Bản thân em thì gia đình cũng khá giả nên em đi du học cũng rất thoải mái không bị áp lực. Chắc đây cũng c...
Label: Giáo_dục__Du_học
Score: 0.931
------------------------------------------------------------
Author: TurnoverSilly2757
Title: Cần lời khuyên cho việc thất bại trong đại học
Content: Em là nam sinh năm 2003, từng học rất tốt và đạt 29 điểm trong kì thi THPTQG năm 2021, nhưng lại bỏ đại học ngoại thương chính quy để học chương trình chuyển tiếp của đh ngoại thương liên kết với trườ...
Label: Giáo_dục__Du_học
Score: 0.953
------------------------------------------------------------
Author: manlovetowatch
Title: Bạn có thể mang con khỉ ra khỏi khu rừng, nhưng không thể mang khu rừng ra khỏi con khỉ!
Content: Betocon xăm kín lưng chạy xe đạp chở theo đầu heo đi nghênh ngang ở Nhật, quay clip up tiktok 😑...
Label: Đời_sống__Nhịp_sống
Score: 0.266
------------------------------------------------------------
Author: WaitRight8056
Title: Cha ruột phóng hoả đốt hai con tại Tây Ninh
Content: https://www.facebook.com/share/p/1CDLRag19N/

Hôm qua tính đăng mà quên mất, đọc vụ này thấy rất thương gia đình nạn nhân, nếu ai muốn hỗ trợ hai cháu thì trong comment có tài khoản của người nhà để ủ...
Label: Thế_giới__Tư_liệu
Score: 0.431
------------------------------------------------------------
Author: Jolly-Panic-5283
Title: Một ngày trôi qua như thế nào
Content: Sáng thức dậy coffee sáng rồi đi làm.
Làm Ot đến 8 giờ tối về nhà , tắm rửa ăn uống 9h.
Lên học làm bài tập đang học liên thông đến 11h.
Bật máy code đến 12h.
xem điện thoại giải trí đến 1h.  ...
Label: Đời_sống__Tổ_ấm
Score: 0.335
------------------------------------------------------------
Author: WaitRight8056
Title: Cha ruột phóng hoả đốt hai con tại Tây Ninh
Content: https://www.facebook.com/share/p/1CDLRag19N/

Hôm qua tính đăng mà quên mất, đọc vụ này thấy rất thương gia đình nạn nhân, nếu ai muốn hỗ trợ hai cháu thì trong comment có tài khoản của người nhà để ủ...
Label: Thế_giới__Tư_liệu
Score: 0.431
------------------------------------------------------------
Author: Sensitive-Ad-751
Title: TRẪM, NAM ĐẾ, NAM KỲ PHỔ ĐỘ-QUANG VINH VỸ ĐẠI! Đem chế độ quân chủ trở lại. TRẪM! NAM ĐẾ! NAM KỲ PHỔ ĐỘ-QUANG VINH VỸ ĐẠI! TRẪM sẽ hồi phục văn minh quân chủ. TRẪM! NAM ĐẾ ngự trị nước Nam.
Content: TRẪM, NAM ĐẾ, NAM KỲ PHỔ ĐỘ-QUANG VINH VỸ ĐẠI! Đem chế độ quân chủ trở lại.

TRẪM! NAM ĐẾ!
NAM KỲ PHỔ ĐỘ-QUANG VINH VỸ ĐẠI!
TRẪM sẽ hồi phục văn minh quân chủ.
TRẪM! NAM ĐẾ ngự trị nước Na...
Label: Giải_trí__Sách
Score: 0.920
------------------------------------------------------------
Author: Emergency_Desk4670
Title: chế độ độc tài của Nicolas Maduro đang lung lay
Content: Tổng thống Trump triển khai ba khu trục hạm Aegis hiện đại USS Gravely, USS Jason Dunham và USS Sampson, cùng hai tàu ngầm tấn công, drones trinh sát cùng hơn 4.000 lính Thủy quân Lục chiến áp sát vùn...
Label: Thế_giới__Quân_sự
Score: 0.933
------------------------------------------------------------
Author: jeremypham
Title: 2 vấn đề về neutral wrist position
Content: Hello mn. Mình đang tập gym nhưng bị gặp 2  vấn đề này không biết sửa ntn.
- Mình không biết góc độ nào mới đúng để tạo ra neutral wrist chính xác nhất. Mình biết neutral wrist thì không được cong cổ ...
Label: Sức_khỏe__Sống_khỏe
Score: 0.501
------------------------------------------------------------
Author: supacarot
Title: Cần tư vấn mua laptop gaming tầm giá 40tr
Content: Chào mọi người, mình cần tư vấn mua laptop gaming tầm giá 45tr đổ lại đáng mua nhất hiện nay ạ. Về độ bền và hiệu năng, thì theo mọi người nên mua model nào nhất ạ...
Label: Khoa_học_công_nghệ__Thiết_bị
Score: 0.761
------------------------------------------------------------
Author: LeeTuneVane
Title: Công thức làm phim chiếu rạp rác rưởi kiếm trăm tỷ kiểu mới: Làm phim chiến tranh yêu lước, ai chê là phản động 3 que
Content: Leak trước cho tụi mày là bộ phim này được nhiên có vài cảnh sẽ để cho mục đích kích đẻ cho đám giới trẻ như bao bộ phim chiến tranh yêu lước gân đây và có thêm đoạn chửi Mỹ nữa...
Label: Giải_trí__Phim
Score: 0.894
------------------------------------------------------------
Author: LeeTuneVane
Title: Các con nái ở thủ đô lại ra nữa khi thấy mấy anh bụ địu diễn xiếc khỉ nữa rồi
Content: Các con nái ở thủ đô lại ra nữa khi thấy mấy anh bụ địu diễn xiếc khỉ nữa rồi

Các con nái ở thủ đô lại ra nữa khi thấy mấy anh bụ địu diễn xiếc khỉ nữa rồi...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.349
------------------------------------------------------------
Author: Forward-Divide8898
Title: Người ăn xin ở Canada
Content: Mọi người cứ thấy dân ăn xin ở Canada là nghĩ Canada nghèo nhưng phải vậy. Mình có bạn ở Canada quay cho mình cảnh dân ăn xin ở Canada, bạn mình nói người ăn xin ở Canada không phải là người già, khuy...
Label: Thế_giới__Cuộc_sống_đó_đây
Score: 0.496
------------------------------------------------------------
Author: vikkidzebe
Title: Ma tuý của các nhà nước độc tài - “một dạng tự mãn rỗng”
Content: “một dạng tự mãn rỗng”

 • Có hãng xe không đồng nghĩa có nền công nghiệp ô tô. Nền công nghiệp ô tô phải được xây dựng trên chuỗi cung ứng linh kiện, công nghệ, hệ sinh thái sản xuất – điều mà Việt N...
Label: Xe__Thị_trường
Score: 0.506
------------------------------------------------------------

In [23]:
df_Reddit['label'].value_counts()

label
Giải_trí__Sách                          1464
Thế_giới__Cuộc_sống_đó_đây              1431
Đời_sống__Bài_học_sống                  1100
Đời_sống__Nhịp_sống                      810
Đời_sống__Tổ_ấm                          781
Thời_sự__80_năm_Quốc_khánh               650
Thế_giới__Tư_liệu                        616
Pháp_luật__Hồ_sơ_phá_án               614
Giáo_dục__Du_học                         534
Khoa_học_công_nghệ__AI                   485
Giáo_dục__Tin_tức                        464
Sức_khỏe__Tin_tức                        359
Thời_sự__Chính_trị                       313
Sức_khỏe__Sống_khỏe                      261
Giải_trí__Giới_sao                       256
Khoa_học_công_nghệ__Thiết_bị             254
Xe__V-Car                                245
Giải_trí__Phim                           224
Thời_sự__Kỷ_nguyên_mới                   214
Khoa_học_công_nghệ__Chuyển_đổi_số        207
Thế_giới__Phân_tích                      203
Kinh_doanh__Kinh_tế_vùng                 192
Du_lịch__Ẩm_thực                         188
Kinh_doanh__Hàng_hóa                     186
Kinh_doanh__Quốc_tế                      159
Kinh_doanh__Vĩ_mô                        141
Du_lịch__Tư_vấn                          135
Kinh_doanh__Doanh_nghiệp                 124
Kinh_doanh__Ebank                        114
Thế_giới__Quân_sự                        109
Giải_trí__Nhạc                           107
Du_lịch__Điểm_đến                        101
Giải_trí__Thời_trang                     100
Xe__Thị_trường                            83
Khoa_học_công_nghệ__Đổi_mới_sáng_tạo      80
Sức_khỏe__Các_bệnh                        78
Bất_động_sản__Thị_trường                  75
Kinh_doanh__NetZero                       66
Thời_sự__Giao_thông                       50
Bất_động_sản__Tư_vấn                      48
Kinh_doanh__Chứng_khoán                   40
Bất_động_sản__Không_gian_sống             38
Sức_khỏe__Vaccine                         23
Pháp_luật__Tư_vấn                          7
Name: count, dtype: int64